# Inverse of matrix

In [1]:
import numpy as np
from scipy import linalg

matrix = np.array([[10, 6], [2, 7]])
matrix

array([[10,  6],
       [ 2,  7]])

In [2]:
type(matrix)

numpy.ndarray

In [3]:
linalg.inv(matrix)

array([[ 0.12068966, -0.10344828],
       [-0.03448276,  0.17241379]])

# Finding Determinant

In [4]:
import numpy as np
from scipy import linalg

matrix = np.array([[4, 9], [3, 5]])
matrix

array([[4, 9],
       [3, 5]])

In [5]:
linalg.det(matrix) #determinante é a diferença entre a multiplicação dos elementos na diagonal (4*5)-(3*9) = -7

-7.000000000000001

# Solving linear systems

In [6]:
import numpy as np
from scipy import linalg

"""
2x + 3y + z = 21
-x + 5y + 4z = 9
3x + 2y + 9z = 6
"""

numArray = np.array([[2, 3, 1], [-1, 5, 4], [3, 2, 9]]) #[x, y, z]
numArrValues = np.array([21, 9, 6]) #resultado do sistema

print(numArray)
print('')
print(numArrValues)

[[ 2  3  1]
 [-1  5  4]
 [ 3  2  9]]

[21  9  6]


In [7]:
linalg.solve(numArray, numArrValues) #resultado de x, y e z

array([ 4.95,  4.35, -1.95])

# Single value decomposition (svd)

In [8]:
import numpy as np
from scipy import linalg

numSvdArr = np.array([[3, 5, 1], [9, 5, 7]])
numSvdArr

array([[3, 5, 1],
       [9, 5, 7]])

In [9]:
numSvdArr.shape

(2, 3)

In [10]:
linalg.svd(numSvdArr)

(array([[-0.37879831,  0.92547925],
        [-0.92547925, -0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [-0.19208294,  0.82977932, -0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))