In [6]:
#import NumPy lib
import numpy as np

In [7]:
#first NumPy array
first_numpy_array = np.array([1, 2, 3, 4])

In [8]:
#print first array
print(first_numpy_array)

[1 2 3 4]


In [9]:
#array with zeros
array_with_zeros = np.zeros((3, 3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
#array with ones
array_with_ones = np.ones((3, 3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#array with empty
array_with_empty = np.empty((2, 3))
array_with_empty

array([[4.67089899e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [12]:
#array with arange method
array_with_arrange = np.arange(12)
array_with_arrange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
#reshape method to change/ create array
array_with_arrange.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
#linspace for linearly (equal) spaced data elements
array_with_linspace = np.linspace(1, 6, 5) #(start of array, end of array, interval (even spaces))
print(array_with_linspace)

[1.   2.25 3.5  4.75 6.  ]


In [15]:
#one dimensional array
oneD_array = np.arange(15)
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [16]:
#two dimensional array
twoD_array = oneD_array.reshape(3, 5) #(rows, cols)
print(twoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [17]:
#three dimensional array
threeD_array = np.arange(27).reshape(3, 3, 3)
print(threeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [19]:
test_array = np.linspace(4, 13, 7)
print(test_array)

[ 4.   5.5  7.   8.5 10.  11.5 13. ]
