In [2]:
import numpy as np

new_cyclist_trials = np.array([[10, 15, 17, 26, 13, 19], [12, 11, 21, 24, 14, 23]])
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [3]:
new_cyclist_trials.ravel() #unify all axes - unifica todos os eixos

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [5]:
new_cyclist_trials.reshape(3, 4) #reshape axes - redesenha os eixos, nesse caso passando de (2L, 6C) para (3L, 4C)

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [6]:
new_cyclist_trials.resize(2, 6) #altera o tamanho do objeto original
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [7]:
np.hsplit(new_cyclist_trials, 2) #divide horizontalmente o array, nesse caso divindo dois eixos 2L, 6C para 2 arrays com 
#                                   2 eixos 2L, 3C, unificando os dois eixos e remodelando

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 23]])]

In [11]:
new_cyclist_1 = np.array([10, 15, 17, 26, 13, 19])
new_cyclist_2 = np.array([12, 11, 21, 24, 14, 23])

np.hstack((new_cyclist_1, new_cyclist_2)) # empilha 2 arrays em um

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

# Broadcasting

In [12]:
# Create two arrays of the same shape, in this case (1L, 4C)
array_a = np.array([2, 3, 5, 8])
array_b = np.array([.3, .3, .3, .3])

In [13]:
# multiply arrays
array_a * array_b

array([0.6, 0.9, 1.5, 2.4])

In [14]:
# create a var with a scalar value
scalar_c = .3

#multiply 1D array with a scalar value
array_a * scalar_c

array([0.6, 0.9, 1.5, 2.4])

In [ ]:
## Only works if their dimensions are the same, or one of them has a dimension of size 1

# Transposing

In [15]:
test_scores = np.array([[83, 71, 57, 63], [54, 68, 81, 45]])
test_scores

array([[83, 71, 57, 63],
       [54, 68, 81, 45]])

In [16]:
test_scores.transpose()

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

# Linear Algebra - Inverse and Trace

In [18]:
inverse_array = np.array([[10, 20], [15, 25]]) # only works with square matrix (matriz quadrada, mesmo numero de linhas e colunas)
inverse_array

array([[10, 20],
       [15, 25]])

In [19]:
np.linalg.inv(inverse_array)

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [20]:
np.trace(inverse_array) #sum of diagonal elements ((0,0) + (1,1) + (2,2) ... + (n,n))

35