In [2]:
import numpy as np

In [3]:
#addition
np.add(45, 20)

65

In [4]:
#subtraction
np.subtract(45, 23)

22

In [5]:
# ndarray multiplication
# create ndarray which contains number of hours worked for 5 days
# hourly rate is 15 USD
np_daily_wage = np.array([7, 9, 13, 8, 11]) * 15

In [6]:
# print hourly wage for each day
print(np_daily_wage)

[105 135 195 120 165]


In [ ]:
# total earning after 5 days
# use sum method to add all data elements of ndarray
sum(np_daily_wage)

# Comparison Operations

In [10]:
#comparison operations
#create ndarray for weekly hours, 5 consecutive weeks hours data
np_weekly_hrs = np.array([23, 41, 55, 47, 38])

In [12]:
#week with more than 40 hours
np_weekly_hrs[np_weekly_hrs>40]

array([41, 55, 47])

In [13]:
#week with more not equals to 40 hours
np_weekly_hrs[np_weekly_hrs!=40]

array([23, 41, 55, 47, 38])

# Logical Operations

In [14]:
#logical AND operation
np.logical_and(np_weekly_hrs>20, np_weekly_hrs<50)

array([ True,  True, False,  True,  True])

In [15]:
#logical NOT operation
np.logical_not(np_weekly_hrs>35)

array([ True, False, False, False, False])

# Indexing

In [17]:
cyclist_trials = np.array([[10, 15, 17, 26], [12, 11, 21, 24]])

first_trial = cyclist_trials[0]
first_trial

array([10, 15, 17, 26])

In [18]:
second_trial = cyclist_trials[1]
second_trial

array([12, 11, 21, 24])

In [19]:
first_cyclist_firstTrial = cyclist_trials[0][0]
first_cyclist_firstTrial

10

In [20]:
first_cyclist_allTrials = cyclist_trials[:, 0]
first_cyclist_allTrials

array([10, 12])

# Slicing

In [21]:
cyclist_trials.shape

(2, 4)

In [22]:
two_cyclist_trial_data = cyclist_trials[:,1:3]
two_cyclist_trial_data

array([[15, 17],
       [11, 21]])

# Iteration

In [23]:
for x in cyclist_trials:
    print(x)

[10 15 17 26]
[12 11 21 24]


In [24]:
for x in two_cyclist_trial_data:
    print(x)

[15 17]
[11 21]


In [25]:
for x in two_cyclist_trial_data:
    print(x+1)

[16 18]
[12 22]


# Indexing with Boolean Arrays

In [33]:
test_scores = np.array([[83, 71, 57, 63, 61], [54, 68, 81, 45, 60]])

passing_score = test_scores>60
not_passing_score = test_scores<=60
passing_score

array([[ True,  True, False,  True,  True],
       [False,  True,  True, False, False]])

In [34]:
test_scores[passing_score]

array([83, 71, 63, 61, 68, 81])

In [35]:
test_scores[not_passing_score]

array([57, 54, 45, 60])